################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

C++M_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
CCM_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
CC_SRCS := 
C_SRCS := 
CXXM_SRCS := 
CYCLO_FILES := 
OBJDUMP_LIST := 
CCM_DEPS := 
C_UPPER_DEPS := 
S_DEPS := 
CXXM_DEPS := 
C_DEPS := 
CC_DEPS := 
SIZE_OUTPUT := 
C++_DEPS := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
CXX_DEPS := 
MAP_FILES := 
S_UPPER_DEPS := 
C++M_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/STM32F4xx_HAL_Driver/Src \
Librerias/lvgl-release-v8.3/demos/benchmark/assets \
Librerias/lvgl-release-v8.3/demos/benchmark \
Librerias/lvgl-release-v8.3/demos/keypad_encoder \
Librerias/lvgl-release-v8.3/demos/music/assets \
Librerias/lvgl-release-v8.3/demos/music \
Librerias/lvgl-release-v8.3/demos/stress \
Librerias/lvgl-release-v8.3/demos/widgets/assets \
Librerias/lvgl-release-v8.3/demos/widgets \
Librerias/lvgl-release-v8.3/env_support/rt-thread \
Librerias/lvgl-release-v8.3/env_support/rt-thread/squareline \
Librerias/lvgl-release-v8.3/examples/anim \
Librerias/lvgl-release-v8.3/examples/assets \
Librerias/lvgl-release-v8.3/examples/assets/emoji \
Librerias/lvgl-release-v8.3/examples/event \
Librerias/lvgl-release-v8.3/examples/get_started \
Librerias/lvgl-release-v8.3/examples/layouts/flex \
Librerias/lvgl-release-v8.3/examples/layouts/grid \
Librerias/lvgl-release-v8.3/examples/libs/bmp \
Librerias/lvgl-release-v8.3/examples/libs/ffmpeg \
Librerias/lvgl-release-v8.3/examples/libs/freetype \
Librerias/lvgl-release-v8.3/examples/libs/gif \
Librerias/lvgl-release-v8.3/examples/libs/png \
Librerias/lvgl-release-v8.3/examples/libs/qrcode \
Librerias/lvgl-release-v8.3/examples/libs/rlottie \
Librerias/lvgl-release-v8.3/examples/libs/sjpg \
Librerias/lvgl-release-v8.3/examples/others/fragment \
Librerias/lvgl-release-v8.3/examples/others/gridnav \
Librerias/lvgl-release-v8.3/examples/others/ime \
Librerias/lvgl-release-v8.3/examples/others/imgfont \
Librerias/lvgl-release-v8.3/examples/others/monkey \
Librerias/lvgl-release-v8.3/examples/others/msg \
Librerias/lvgl-release-v8.3/examples/others/snapshot \
Librerias/lvgl-release-v8.3/examples/porting \
Librerias/lvgl-release-v8.3/examples/scroll \
Librerias/lvgl-release-v8.3/examples/styles \
Librerias/lvgl-release-v8.3/examples/widgets/animimg \
Librerias/lvgl-release-v8.3/examples/widgets/arc \
Librerias/lvgl-release-v8.3/examples/widgets/bar \
Librerias/lvgl-release-v8.3/examples/widgets/btn \
Librerias/lvgl-release-v8.3/examples/widgets/btnmatrix \
Librerias/lvgl-release-v8.3/examples/widgets/calendar \
Librerias/lvgl-release-v8.3/examples/widgets/canvas \
Librerias/lvgl-release-v8.3/examples/widgets/chart \
Librerias/lvgl-release-v8.3/examples/widgets/checkbox \
Librerias/lvgl-release-v8.3/examples/widgets/colorwheel \
Librerias/lvgl-release-v8.3/examples/widgets/dropdown \
Librerias/lvgl-release-v8.3/examples/widgets/img \
Librerias/lvgl-release-v8.3/examples/widgets/imgbtn \
Librerias/lvgl-release-v8.3/examples/widgets/keyboard \
Librerias/lvgl-release-v8.3/examples/widgets/label \
Librerias/lvgl-release-v8.3/examples/widgets/led \
Librerias/lvgl-release-v8.3/examples/widgets/line \
Librerias/lvgl-release-v8.3/examples/widgets/list \
Librerias/lvgl-release-v8.3/examples/widgets/menu \
Librerias/lvgl-release-v8.3/examples/widgets/meter \
Librerias/lvgl-release-v8.3/examples/widgets/msgbox \
Librerias/lvgl-release-v8.3/examples/widgets/obj \
Librerias/lvgl-release-v8.3/examples/widgets/roller \
Librerias/lvgl-release-v8.3/examples/widgets/slider \
Librerias/lvgl-release-v8.3/examples/widgets/span \
Librerias/lvgl-release-v8.3/examples/widgets/spinbox \
Librerias/lvgl-release-v8.3/examples/widgets/spinner \
Librerias/lvgl-release-v8.3/examples/widgets/switch \
Librerias/lvgl-release-v8.3/examples/widgets/table \
Librerias/lvgl-release-v8.3/examples/widgets/tabview \
Librerias/lvgl-release-v8.3/examples/widgets/textarea \
Librerias/lvgl-release-v8.3/examples/widgets/tileview \
Librerias/lvgl-release-v8.3/examples/widgets/win \
Librerias/lvgl-release-v8.3/src/core \
Librerias/lvgl-release-v8.3/src/draw/arm2d \
Librerias/lvgl-release-v8.3/src/draw \
Librerias/lvgl-release-v8.3/src/draw/nxp/pxp \
Librerias/lvgl-release-v8.3/src/draw/nxp/vglite \
Librerias/lvgl-release-v8.3/src/draw/renesas \
Librerias/lvgl-release-v8.3/src/draw/sdl \
Librerias/lvgl-release-v8.3/src/draw/stm32_dma2d \
Librerias/lvgl-release-v8.3/src/draw/sw \
Librerias/lvgl-release-v8.3/src/draw/swm341_dma2d \
Librerias/lvgl-release-v8.3/src/extra/layouts/flex \
Librerias/lvgl-release-v8.3/src/extra/layouts/grid \
Librerias/lvgl-release-v8.3/src/extra/libs/bmp \
Librerias/lvgl-release-v8.3/src/extra/libs/ffmpeg \
Librerias/lvgl-release-v8.3/src/extra/libs/freetype \
Librerias/lvgl-release-v8.3/src/extra/libs/fsdrv \
Librerias/lvgl-release-v8.3/src/extra/libs/gif \
Librerias/lvgl-release-v8.3/src/extra/libs/png \
Librerias/lvgl-release-v8.3/src/extra/libs/qrcode \
Librerias/lvgl-release-v8.3/src/extra/libs/rlottie \
Librerias/lvgl-release-v8.3/src/extra/libs/sjpg \
Librerias/lvgl-release-v8.3/src/extra/libs/tiny_ttf \
Librerias/lvgl-release-v8.3/src/extra \
Librerias/lvgl-release-v8.3/src/extra/others/fragment \
Librerias/lvgl-release-v8.3/src/extra/others/gridnav \
Librerias/lvgl-release-v8.3/src/extra/others/ime \
Librerias/lvgl-release-v8.3/src/extra/others/imgfont \
Librerias/lvgl-release-v8.3/src/extra/others/monkey \
Librerias/lvgl-release-v8.3/src/extra/others/msg \
Librerias/lvgl-release-v8.3/src/extra/others/snapshot \
Librerias/lvgl-release-v8.3/src/extra/themes/basic \
Librerias/lvgl-release-v8.3/src/extra/themes/default \
Librerias/lvgl-release-v8.3/src/extra/themes/mono \
Librerias/lvgl-release-v8.3/src/extra/widgets/animimg \
Librerias/lvgl-release-v8.3/src/extra/widgets/calendar \
Librerias/lvgl-release-v8.3/src/extra/widgets/chart \
Librerias/lvgl-release-v8.3/src/extra/widgets/colorwheel \
Librerias/lvgl-release-v8.3/src/extra/widgets/imgbtn \
Librerias/lvgl-release-v8.3/src/extra/widgets/keyboard \
Librerias/lvgl-release-v8.3/src/extra/widgets/led \
Librerias/lvgl-release-v8.3/src/extra/widgets/list \
Librerias/lvgl-release-v8.3/src/extra/widgets/menu \
Librerias/lvgl-release-v8.3/src/extra/widgets/meter \
Librerias/lvgl-release-v8.3/src/extra/widgets/msgbox \
Librerias/lvgl-release-v8.3/src/extra/widgets/span \
Librerias/lvgl-release-v8.3/src/extra/widgets/spinbox \
Librerias/lvgl-release-v8.3/src/extra/widgets/spinner \
Librerias/lvgl-release-v8.3/src/extra/widgets/tabview \
Librerias/lvgl-release-v8.3/src/extra/widgets/tileview \
Librerias/lvgl-release-v8.3/src/extra/widgets/win \
Librerias/lvgl-release-v8.3/src/font \
Librerias/lvgl-release-v8.3/src/hal \
Librerias/lvgl-release-v8.3/src/misc \
Librerias/lvgl-release-v8.3/src/widgets \
Librerias/lvgl-release-v8.3/tests/makefile \
Librerias/lvgl-release-v8.3/tests/src \
Librerias/lvgl-release-v8.3/tests/src/test_cases \
Librerias/lvgl-release-v8.3/tests/src/test_fonts \
Librerias/lvgl-release-v8.3/tests/unity \

